// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0iF-1fyf0RmaAGO0P2JEme_im0hAjpE',
    appId: '1:878089355365:android:1f8f85b385df6efc74068c',
    messagingSenderId: '878089355365',
    projectId: 'newteam-d85e9',
    storageBucket: 'newteam-d85e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEp_Q1PJb36DN1zBLu0BuFPVlDv3AoO2A',
    appId: '1:878089355365:ios:0379f60f455f8aa674068c',
    messagingSenderId: '878089355365',
    projectId: 'newteam-d85e9',
    storageBucket: 'newteam-d85e9.appspot.com',
    iosBundleId: 'com.example.newTeam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVjF4sMKZRynKUGEp83XEPS8AtBZ7kmpk',
    appId: '1:878089355365:web:60c564412ff5019974068c',
    messagingSenderId: '878089355365',
    projectId: 'newteam-d85e9',
    authDomain: 'newteam-d85e9.firebaseapp.com',
    storageBucket: 'newteam-d85e9.appspot.com',
  );

}